-- Your SQL goes here
-- CREATE TABLE collections (
--   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
--   name VARCHAR NOT NULL,
--   status BOOLEAN NOT NULL DEFAULT 0
-- )

CREATE TABLE IF NOT EXISTS  collections (
  id INTEGER NOT NULL PRIMARY KEY,
  uuid VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  is_open BOOLEAN NOT NULL DEFAULT 0,
  status BOOLEAN NOT NULL DEFAULT 0,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);